// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdg-RUrhrCzq7feI8p73sYM-bxyIG98g',
    appId: '1:738770974640:web:5289fe07d2d12bc3ddc875',
    messagingSenderId: '738770974640',
    projectId: 'assignment10-f9956',
    authDomain: 'assignment10-f9956.firebaseapp.com',
    storageBucket: 'assignment10-f9956.appspot.com',
    measurementId: 'G-KWLFL7146T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-dg6_m4g0o-xOQzaV9jP4PHsWKXby9U',
    appId: '1:738770974640:android:06b609d40b57e36bddc875',
    messagingSenderId: '738770974640',
    projectId: 'assignment10-f9956',
    storageBucket: 'assignment10-f9956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDOfM3ZZdnvNic60G5pNrFzFIDSSc1bvo',
    appId: '1:738770974640:ios:4287d5a7fa86ef64ddc875',
    messagingSenderId: '738770974640',
    projectId: 'assignment10-f9956',
    storageBucket: 'assignment10-f9956.appspot.com',
    iosBundleId: 'com.example.assignment10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDOfM3ZZdnvNic60G5pNrFzFIDSSc1bvo',
    appId: '1:738770974640:ios:4287d5a7fa86ef64ddc875',
    messagingSenderId: '738770974640',
    projectId: 'assignment10-f9956',
    storageBucket: 'assignment10-f9956.appspot.com',
    iosBundleId: 'com.example.assignment10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmdg-RUrhrCzq7feI8p73sYM-bxyIG98g',
    appId: '1:738770974640:web:2a545f0e2502f560ddc875',
    messagingSenderId: '738770974640',
    projectId: 'assignment10-f9956',
    authDomain: 'assignment10-f9956.firebaseapp.com',
    storageBucket: 'assignment10-f9956.appspot.com',
    measurementId: 'G-FEF3BWXXTS',
  );
}
